[package]

name = "intovec"
version = "0.0.2"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
description = "IntoVec, a trait for converting types into Vec, avoiding copies when possible."
license = "MIT"

